spring.application.name=OCTQuiz
server.port=80
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=50
debug=false
server.forward-headers-strategy=framework
server.servlet.context-path=/octquiz
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.name=JSESSIONID_OCTQUIZ
server.servlet.session.cookie.same-site=lax
maintenance.password=${MAINTENANCE_PASSWORD}
spring.web.resources.add-mappings=true

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=when-authorized
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_SENDER}
admin.mail=${EMAIL_ADMIN}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Dimensione massima file upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB

bot.api.url=${BOT_URL:http://localhost:8245/request}